version: "3.8"

networks:
  db-net:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: yenyeny1/mysql:latest
    restart: always
    ports: 
      - 3306:3306
    networks:
      - db-net
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE : radio
      MYSQL_USER: visualradio
      MYSQL_PASSWORD: visualradio
      MYSQL_ROOT_PASSWORD: visualradio
  visual-radio:
    image: yenyeny1/visual-radio:0.1
    container_name: visual-radio
    restart: always
    expose:
      - 5000
    networks:
      - db-net
    depends_on:
      - mysql